### ISSUE TITLE
Receiving AWS::SessionStore::DynamoDB::InvalidIDError: Corrupt Session ID! for valid hmac ids

### ISSUE THREAD

**Issue by reinaldob** [aws/aws-sessionstore-dynamodb-ruby#21]
Hello!

First of all, thanks for contributed to open source with this library, it's really helpful.

I am seeing some `Corrupt Session ID!` on production, but what concerns me it's the hmac, seems to be a valid one.

I've tried to debug the errors looking here: https://github.com/aws/aws-sessionstore-dynamodb-ruby/blob/master/lib/aws/session_store/dynamo_db/rack_middleware.rb#L67

But I couldn't simulated anymore, is there anyone having the same problem?

I've tested using `cURL` and it passes, but it raised errors in production from where I copied the cookie I was using for test.

Thanks again!

**Comment by awood45** [comment]
I haven't heard of this issue before - are you saying that it happened for a while and is no longer happening? Do you have a way to reproduce?

**Comment by reinaldob** [comment]
@awood45 It was happening until a month ago, but It was as hundreds of times, as those requests are all from google bot.

I've got some cookies and tried with cURL and couldn't simulate them 😕
