### ISSUE TITLE
Make a new release please

### ISSUE THREAD

**Issue by seven1m** [aws/aws-sessionstore-dynamodb-ruby#24]
The `master` branch is way ahead of the latest '1.0.0' release and it would be nice to install this from Rubygems.org rather than directly from GitHub. Thanks!

**Comment by mullermp** [comment]
Hey @seven1m, to be honest with you, I think this library is on life support. The current version has about 1,150 downloads over a 3 year period. The last commits since Aug 2017 were for dependencies/documentation and no additional feature.

What is your use case for this gem? Is this something you'd be interested in owning and improving?

**Comment by seven1m** [comment]
Thanks for the response. We're in the process of migrating from Rails cookie-based session storage to DynamoDB-backed storage. As far as I can tell, this gem does what we need. We are making a few tweaks internally to modify the storage format, but the foundation is good in this gem it seems.

Is there a recommended alternative for a Rails app that needs to store sessions in DynamoDB, or are you just saying the demand doesn't seem to be there thus the attention is waning?

**Comment by mullermp** [comment]
Based on usage of this gem, it doesn't seem to be a popular choice among customers. The Ruby SDK team is very small, and we own many products, so it's hard to keep these kinds of libraries up to date. Just curious, as a customer, why is DynamoDB your preferred session choice in Rails? As a thought, we could consider migrating this functionality to our [aws-sdk-rails](https://github.com/aws/aws-sdk-rails) gem, decreasing the amount of packages we own while still providing the functionality.

**Comment by seven1m** [comment]
We need to add the ability to our product to log out specific sessions/devices, among other things. We could use `activerecord-session_store` but would rather not use SQL for something that's key-value. DynamoDB seems like a good fit.

We also like the ability to set it and forget it -- DynamoDB will scale automatically for our needs unlike something like Redis.

I think it would be a shame for this gem to just go away, so if you need a maintainer, I'd be willing to help out. If you think moving this code to the aws-sdk-rails gem would help it get some love, then that's ok too.

Thanks for the conversation around this!

**Comment by mullermp** [comment]
Your use case makes sense. I'll talk with leadership on my side to see what the support plan for this gem is.

As for moving this to aws-sdk-rails, this gem also supports rack applications, so moving it would effectively deprecate that functionality. I'm not sure how popular rack applications are, compared to rails, these days.

**Comment by mullermp** [comment]
Hey @seven1m, I have come up with a plan for this gem. I see that it's also still using V2 of the SDK which is end of life in a couple weeks. The plan will be to major version bump this gem with some breaking changes and upgrades, and move the rails-specific functionality in aws-sdk-rails. We'll also put some effort into improving aws-sdk-rails with new features, including pulling this gem as a dependency.

**Comment by seven1m** [comment]
Sounds great! BTW we are using the gem with `aws-sdk-core` version 3.100.0 and it works fine.

**Comment by mullermp** [comment]
@seven1m We just pushed out a version 2 of this, which includes some fixes as well as moving Rails support to aws-sdk-rails where it will be better supported. We'll be releasing a new version of that shortly. https://github.com/aws/aws-sdk-rails/

**Comment by mullermp** [comment]
Ran into some issues testing aws-sdk-rails; I will get that release out this week.
