### ISSUE TITLE
Upgrade to Rack 3

### ISSUE THREAD

**Issue by wildjcrt** [aws/aws-sessionstore-dynamodb-ruby#28]
Rack 3 released. Is there any plan to upgrade? Thanks
Here is the [Rack 3 Upgrade Guide](https://github.com/rack/rack/blob/main/UPGRADE-GUIDE.md)

**Comment by mullermp** [comment]
It's not high on our priority list, but I'll leave this open as a feature request.

**Comment by mullermp** [comment]
I've loosened the rack requirements for this package and used the rack-session dependency. This should allow for rack 3 usage. If there is issue, please reopen.

https://github.com/aws/aws-sessionstore-dynamodb-ruby/pull/34
