### ISSUE TITLE
Session object not compatible with what Rails 5.2 expects.

### ISSUE THREAD

**Issue by patrickquigley102** [aws/aws-sessionstore-dynamodb-ruby#29]
Hey :wave: 

Thank you for authoring the gem. It's great.

```
# This does not work when using this gem but does with Cookie and DB store
session[:session_id]

# This does work, so there is a workaround
# But due to this change, for Rails 5.2 at least, this gem is not a plug and play option for some
session.id
```

Duplicate issue to another storage provider so I will link to that in the hope that it's enough information.

However, that makes this a terse issue report :sweat_smile:  Anything else you need I am willing to help!

https://github.com/petergoldstein/dalli/issues/765

**Comment by mullermp** [comment]
Thanks for opening an issue. I'm not quite sure I follow. I think this is related to Rack and not Rails. What Rack version are you using?

**Comment by mullermp** [comment]
Rack 3 was recently released, and we received a feature request for it, but I don't see a `Session::Abstract::Persisted` equivalent.

Is this gem "plug and play" with newer rails versions (are you able to upgrade to Rails 6 or Rails 7?)

**Comment by mullermp** [comment]
A stack trace of the error would also be helpful for me to look through everything.

**Comment by patrickquigley102** [comment]
Hey Matt.

The linked issue links to the code in the Rails gem which assumes that `session[:session_id]` returns an object that responds to the `public_id` message. The object return by this gem is an instance of a `String`, resulting in a no method error. The error and cause are identical to the linked issue. Rails and Rack are both in the call stack for sure but, the root cause is this middleware and what it gives to Rails.

I've no need to upgrade Rails to fix this bug, as there is a workaround as described in the initial description. Also I do not have support from my employer to do that currently, for the application in question (as much as I'd like too).

I can spend the time gathering a stack trace from a `rails new` app in Rails 5.2. If you think that is worth the time. However, it sounds like maybe you do not consider 5.2 supported and/or this issue is confirmed to not occur in Rails 6 & 7; although both are ambiguous to me. If both are true, and we have a workaround now documented in this issue for 5.2, how'd you like proceed?

**Comment by mullermp** [comment]
If this issue is only happening in Rails 5.2 and not in newer Rails versions like 6 or 7, I don't know if a fix is necessary provided there is a work around (using `session.id` as you stated?). If it's happening at every version, then I would like to get a fix. I'll need to allocate some time to test this with newer Rails and come up with a solution, unless you're willing to help confirm it occurs in new rails. It's a matter of prioritization from my side, I'm currently entangled on a larger SDK project.

**Comment by patrickquigley102** [comment]
I think we should close the issue. Old version of Rails and a workaround as you state.

**Comment by mullermp** [comment]
@patrickquigley102 I'm sorry I never got to this. Does it work for new versions of rails? If so, I agree, we can close.
