### ISSUE TITLE
aws-sdk v2? 

### ISSUE THREAD

**Issue by phstc** [aws/aws-sessionstore-dynamodb-ruby#7]
Hey

Is there any plan to bump it to use the aws-sdk v2?

**Comment by awood45** [comment]
There wasn't a plan in place, but this is definitely a feature request we can consider.

**Comment by phstc** [comment]
@awood45 cool. 

> his is definitely a feature request we can consider.

Taking about feature requests, maybe the new DynamoDB TTL could be a good replacement for `rake dynamo_db:collect_garbage`?

**Comment by JDutil** [comment]
@phstc @awood45 I've got a PR #9 for this update.

**Comment by dkoprov** [comment]
Also it would be fine you update a rake dependency not to be tied to version 1 `~> 1.0`.
Thank you! Waiting for the update, because right now I have a versions conflict on bundler install and can not merge gem into our project.

**Comment by JDutil** [comment]
@dkoprov I updated `rake` but it was at 10.0 not 1.0 so I think you meant `rack` which I've bumped from `~> 1.0` to `>= 1.6.4` as well.

**Comment by dkoprov** [comment]
@JDutil sure, I misspelled id in the end of working day. Thank you!

**Comment by cjyclaire** [comment]
[Latest release)[https://github.com/aws/aws-sessionstore-dynamodb-ruby/releases/tag/1.0.0] adds support for V2 of SDK, thanks to all ;) closing
